services:
  - type: web
    name: youtube-downloader-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: youtube-downloader-api
          property: port
    autoDeploy: true
    healthCheckPath: /health